FROM node:20.4 as ui_build

ARG TARGETARCH
ARG NOMAD_VERSION

WORKDIR /go/src/github.com/hashicorp/

RUN git config --global user.email "mail@shipyard.run" && \
  git config --global user.name "Shipyard Bot"

RUN git clone https://github.com/hashicorp/nomad.git && \
  cd nomad && \
  git checkout v${NOMAD_VERSION}

WORKDIR /go/src/github.com/hashicorp/nomad

RUN make ember-dist
