FROM shipyardrun/tools:latest

ENV TERM=xterm-256color
ENV SQUASH_VERSION=v0.5.18
ENV LOOP_VERSION=v0.0.1
ENV GLOO_VERSION=v0.20.8
ENV PATH "$HOME/.wasme/bin:$PATH"

# Install Squash
RUN curl -sL https://github.com/solo-io/squash/releases/download/$SQUASH_VERSION/squashctl-linux -o squashctl && \
    mv squashctl /usr/local/bin && \
    chmod +x /usr/local/bin/squashctl

# Install Gloo CLI
RUN curl -sL https://github.com/solo-io/gloo/releases/download/$GLOO_VERSION/glooctl-linux-amd64 -o glooctl && \
    mv glooctl /usr/local/bin && \
    chmod +x /usr/local/bin/glooctl

# Install preview of Loop CLI
RUN curl -sL https://github.com/solo-io/demos-gloo/releases/download/$LOOP_VERSION/loopctl-linux-amd64 -o  loopctl && \
    mv loopctl /usr/local/bin && \
    chmod +x /usr/local/bin/loopctl    

# Install WASME
RUN curl -sL https://run.solo.io/wasme/install | sh